// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnehvoofmocrnjrovzcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZWh2b29mbW9jcm5qcm92emN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODgzNzQsImV4cCI6MjA1MzA2NDM3NH0.FGuEqwoQWTupsnyeGqw0f6ASx6SsLrZ8fjyk_jcv6dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);